### ISSUE TITLE
Uncaught TypeError due to BaseEvent

### ISSUE THREAD

**Issue by fritzmg** [FriendsOfSymfony/FOSHttpCache#525] opened 2022-03-16 08:24 UTC
If you are running Symfony 3 and you also install `symfony/contracts` (or a third party dependency happens to also require `symfony/contracts`) the following error will occur:

```
Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, instance of FOS\HttpCache\SymfonyCache\CacheEvent given, 
called in vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php on line 154 and 
defined in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:37 
```

This is because the `BaseEvent` is defined like this

```php
namespace FOS\HttpCache;

use Symfony\Component\EventDispatcher\Event as OldEvent;
use Symfony\Contracts\EventDispatcher\Event as ContractEvent;

if (class_exists(ContractEvent::class)) {
    class BaseEvent extends ContractEvent
    {
    }
} else {
    /**
     * @codeCoverageIgnore
     * @ignore This is purely for 3.4 comparability.
     */
    class BaseEvent extends OldEvent
    {
    }
}
```

It checks for the existence of the contract event class and uses that then - even though the _actually_ installed `symfony/event-dispatcher` will still use the _old_ event class.

_Note:_ I am opening this just for reference in case anyone stumbles over this. Support for Symfony 3 has ended and `friendsofsymfony/http-cache` `2.13.0` has already a minimum dependency of `^4.3` on `symfony/event-dispatcher` where this issue won't occur. This issue only ocurs in  `symfony/event-dispatcher` `2.12.0`, which is the maximum version you can install with Symfony 3.x - and I don't really expect there to be a `2.12.1` release which would turn the `BaseEvent` around like so:

```php
namespace FOS\HttpCache;

use Symfony\Component\EventDispatcher\Event as OldEvent;
use Symfony\Contracts\EventDispatcher\Event as ContractEvent;

if (class_exists(OldEvent::class)) {
    /**
     * @codeCoverageIgnore
     * @ignore This is purely for 3.4 comparability.
     */
    class BaseEvent extends OldEvent
    {
    }
} else {
    class BaseEvent extends ContractEvent
    {
    }
}
```

which would fix the issue. But you can manually patch the file this way if you need to.

**Comment by dbu** [comment] 2022-03-16 09:30
oh, you are right we should have done that the other way around.

if it helps you, i can create a 2.12 branch where we can do the fix as 2.12.1, so you don't need to use a patched version.

**Comment by fritzmg** [comment] 2022-03-16 10:29
It's not a huge deal for me, as it only concerns legacy projects that need to be updated at some point anyway. But if you find the time it would be appreciated :). This should also be merged into `master` then, in case anyone extends from the BaseEvent.

**Comment by dbu** [comment] 2022-03-16 11:00
there you go: https://github.com/FriendsOfSymfony/FOSHttpCache/releases/tag/2.12.1

about master: i wonder if the BaseEvent makes sense to keep at all - as we only install with symfony 4.3 or newer, we will always extend the contract event, no?

**Comment by fritzmg** [comment] 2022-03-16 11:02
Sure but someone else could rely on it and extend from it (for whatever reason) - I don't know if your BC promise covers that though 😁. Other than that it could be removed, yes.

**Comment by dbu** [comment] 2022-03-16 11:08
thanks. BaseEvent was not marked as internal, but was intended like that. i am removing it, would be quite weird to rely on it for a consumer of the library.

**Closed by dbu** 2022-03-16 11:08 UTC

**Comment by fritzmg** [comment] 2022-03-16 11:10
Thank you :)
