### ISSUE TITLE
Weird problem: same code works fine with mod_php5, but not with PHPFPM

### ISSUE THREAD

**Issue by ilukac** [FriendsOfSymfony/FOSHttpCache#215] opened 2015-06-17 12:43 UTC
The isInternalRequest() in
https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/SymfonyCache/UserContextSubscriber.php#L97
is behaving differently with PHPFPM

**Comment by stof** [comment] 2015-06-17 12:46
What do you mean by ``is behaving differently with PHPFPM`` ? Can you explain what the different behaviors are ?

**Comment by ilukac** [comment] 2015-06-17 12:48
With mod_php5 it behaves normal, returns true for a sub-request. With FPM it returns false.

**Comment by stof** [comment] 2015-06-17 12:50
This seems really weird. subrequests are not going staying inside the PHP process, so there is no reason to have a different value for PHP-FPM or mod_php

**Comment by ilukac** [comment] 2015-06-17 12:53
Btw, this is in prod env, might be some difference in execution after all?

**Comment by hpatoio** [comment] 2015-06-17 16:49
Can you please tell us a bit more about your infrastructure setup ? And what exactly you change between the 2 setup ?

**Comment by dbu** [comment] 2015-06-18 06:57
we run the tests with hhvm too. if the tests run through for you, we might
not cover some case. otherwise there is a difference in the setup. if you
can provide a new failing test case, that would be easiest to debug

**Comment by ilukac** [comment] 2015-06-19 10:13
We are still trying to debug it, which is quite difficult in production where we only see the problem. It's possible that it is not related to FOSHttpCache. I'll get back to you if we have some failing test ready...

**Comment by dbu** [comment] 2015-07-29 07:25
@ilukac any updates on this one?

i remember having been puzzled by fatal errors happening inside kernel->terminate being a problem with only one of hhvm or stock php, not sure which one it was.

**Comment by ilukac** [comment] 2015-07-29 07:31
Currently under-capacitated to dig into this :)

**Comment by dbu** [comment] 2015-08-15 15:53
i close this for now, but feel free to reopen if you find more, or just do a PR with a test demonstrating the problem. even if its not a bug on our side, if its something that is likely to go wrong, you could add something to the FAQ section we plan for the doc in #210...

**Closed by dbu** 2015-08-15 15:53 UTC
