### ISSUE TITLE
SymfonyResponseTagger::tagSymfonyResponse() uses hardcoded glue.

### ISSUE THREAD

**Issue by das-peter** [FriendsOfSymfony/FOSHttpCache#540] opened 2022-11-14 15:38 UTC
[SymfonyResponseTagger::tagSymfonyResponse() ](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/929a56a0dd57b372ed701f9c6611fefc9e4a8163/src/Http/SymfonyResponseTagger.php#L37) uses a comma as the hardcoded glue in order to split n merge tags onto a request:
```php
$this->addTags(explode(',', $response->headers->get($this->getTagsHeaderName())));
```

Unfortunately this collides with the fact that glue is easily configurable [CommaSeparatedTagHeaderFormatter](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/2.x/src/TagHeaderFormatter/CommaSeparatedTagHeaderFormatter.php) and the bundle even automatically changes the glue to space in case varnish xkey is used for purging [Configuration](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/929a56a0dd57b372ed701f9c6611fefc9e4a8163/src/DependencyInjection/Configuration.php#L182):
```php
            // Determine the default separator for the tags header, depending on whether we use BAN or xkey
            ->validate()
                ->ifTrue(
                    function ($v) {
                        return empty($v['tags']['separator']);
                    }
                )
                ->then(function ($v) {
                    $v['tags']['separator'] = $this->isVarnishXkey($v) ? ' ' : ',';

                    return $v;
                })
```

Unfortunately I don't think there's a quick solution to this since the [TagHeaderFormatter Interface](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/2.x/src/TagHeaderFormatter/TagHeaderFormatter.php) currently doesn't provide any way to determine the glue.
The cleanest solution I can think of would be to expand the TagHeaderFormatter Inteface with a method that splits a header line. This should be fully transparent for consumers and quite trivial to implement since the implementing class should be very much aware how it is configured and how it has to split a tag header it essentially produced.

So I'd propose a counterpart to `TagHeaderFormatter::getTagsHeaderValue()`

```php
    /**
     * Get the tag array from an HTTP tag header.
     *
     * This extracts all tags from a HTTP tag header and ensures correct encoding.
     *
     * @return string[]
     */
    public function getTagsHeaderArray(string $header): array;
```

I'm aware this is a upstream change and would need to be handled there, I'd like to get feedback from a "consumer" first though.

**Comment by dbu** [comment] 2022-12-01 08:54
hi @das-peter , busy times... i now had a look at this, and i think the problem is that the SymfonyResponseTagger has not been updated when we refactored [ResponseTagger](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/ec878d68b8444077612942ffcdda59538e99579d/src/ResponseTagger.php#L154). that was a refactoring for FOSHttpCache 2.0, so it is available.

imho the fix is to use the getTagsHeaderValue method of the base class in SymfonyResponseTagger. 

i would consider that a bugfix - it would only create problems if somebody configured a different separator and then relies on still getting the default separator...

@Toflar do you see any issue with using that? i think it should be alright.

**Comment by dbu** [comment] 2022-12-01 08:57
oh wait, its not about generating the header, that is already correct. the problem is with how we merge tags. i will have a look.

**Comment by dbu** [comment] 2022-12-01 10:17
this is my current state. i realized we have the same problem with the symfony built-in http cache... https://github.com/FriendsOfSymfony/FOSHttpCache/pull/541

**Comment by das-peter** [comment] 2022-12-01 10:31
@dbu Thank you very much for your time - very much appreciated! Let me know if I can help with anything.
#541 Looks pretty great to me.

**Comment by dbu** [comment] 2022-12-01 11:12
fixed in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/releases/tag/2.14.0

**Closed as completed by dbu** 2022-12-01 11:12 UTC
