### ISSUE TITLE
Unable to find the controller for path "/_fos_user_context_hash"

### ISSUE THREAD

**Issue by supasteev0** [FriendsOfSymfony/FOSHttpCache#264] opened 2015-12-07 09:44 UTC
I am using fos http cache bundle one an ez project.
There are some pages with a X-User-Hash Vary header as well as some ESI (4 or 5 depending on pages)  with a user Vary header.
On some pages, some ESI crash randomly with a 404 when browsing behind Varnish.
The sf log returns the following error : 

request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/_fos_user_context_hash". The route is wrongly configured." at /xxx/ezpublish/bootstrap.php.cache line 3088 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/_fos_user_context_hash\". The route is wrongly configured. at /xxx/ezpublish/bootstrap.php.cache:3088)"} 

I checked Varnishlog and the /_fos_user_context_hash route seems to be called correctly by Varnish.

You should also be aware that we created our own Vary header with a custom route as we needed cache variations on both user roles or user id, depending on the case.

Any idea where this problem could come from ?

**Comment by dbu** [comment] 2015-12-07 10:01
hm, there is the event listener https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/1.3/EventListener/UserContextSubscriber.php that should interrupt hash lookup requests - there indeed is no controller. this looks as if the listener does not see the request. the method and accept header of the hash lookup can be overridden in configuration: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/1.3/DependencyInjection/FOSHttpCacheExtension.php#L186-L187

i am not sure if you really need to change how the system works. for pages that depend on the exact user, you could just vary on the cookie instead of vary on the hash. then varnish does not need to be aware of different cases, and you either vary on the hash or on the cookie (= session = user).

**Comment by supasteev0** [comment] 2015-12-07 10:14
Well I've been told that varying ESI on cookie was not really something that is handled very well by Varnish, that's why we did it that way. 
Moreover, we didn't change the way the system works : we use the native event listener for User-hash (roles) Vary, and just created our own route (so no listener, just a custom route calling a generateHash controller action) for User unique cache.

**Comment by dbu** [comment] 2015-12-07 10:51
ah, ok. i did not know that. i would expect it to work fine - the thing is that if you generally do that with every page, you end up with caching per user which will give a very low cache hit rate. if it does not work for ESI, that would be a really annoying bug.

anyways, can you see if the requests you send are using the correct accept headers? can you debug why the listener does not stop the request short before it tries to find the controller?

**Comment by supasteev0** [comment] 2015-12-07 12:41
OK, I did some debugging : 

- I added some log in the RequestListener : 
```php
 if(strpos($event->getRequest()->getPathInfo(),'user_context') > 0)
            $this->logger->addNotice('Route is user context');

        if (!$this->requestMatcher->matches($event->getRequest())) {
            if(strpos($event->getRequest()->getPathInfo(),'user_context') > 0)
                $this->logger->addNotice('Route user context does not match -->'.$event->getRequest()->getPathInfo());
            return;
        }
```

And got this in sf log : 
[2015-12-07 13:31:47] app.NOTICE: Route is user context [] []
[2015-12-07 13:31:47] app.NOTICE: Route user context does not match -->/_fos_user_context_hash [] []

And here is the corresponding varnish log : 

 << Request  >> 295062    
-   Begin          req 295048 esi
-   Timestamp      Start: 1449491508.178132 0.000000 0.000000
-   ReqStart       127.0.0.1 54664
-   VCL_call       RECV
-   LostHeader     X-Foncia-Cookie-Accepted:
-   LostHeader     X-Foncia-Admin:
-   LostHeader     Surrogate-Capability:
-   LostHeader     Accept-Encoding:
-   LostHeader     x-fos-original-url:
-   LostHeader     x-fos-original-accept:
-   LostHeader     x-fos-original-cookie:
-   LostHeader     x-fos-original-foncia-admin:
-   LostHeader     cookie:
-   LostHeader     cookie:
-   LostHeader     cookie:
-   LostHeader     cookie:
-   LostHeader     cookie:
-   LostHeader     accept:
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   Debug          "XXXX MISS"
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 295063 fetch
-   Timestamp      Fetch: 1449491508.456451 0.278319 0.278319
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Date: Mon, 07 Dec 2015 12:31:48 GMT
-   RespHeader     Server: Apache/2.2.15 (CentOS)
-   RespHeader     X-Powered-By: PHP/5.6.10
-   RespHeader     Cache-Control: public, s-maxage=604800
-   RespHeader     X-Location-Id: 105 106 107 108 618 620 623 624 626 628 630 632 109 110 111 112 619 621 622 625 627 629 631 633 673 79 80 81 82 83 101 102 104 634 635 636 637 638 639 640 641 642 187 188 189 217 218 219 259 260 261 289 290 291 319 320 321 349 350 351 379 
-   RespHeader     Vary: Cookie,Accept-Encoding,Authorization
-   RespHeader     Content-Encoding: gzip
-   RespHeader     Access-Control-Allow-Origin: *
-   RespHeader     X-Front-Hostname: SDD110D012FEL_2
-   RespHeader     Content-Length: 1645
-   RespHeader     Content-Type: text/html; charset=UTF-8
-   RespHeader     X-Varnish-Backend: ezpublish2
-   RespHeader     X-Varnish: 295062 295063
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespUnset      Vary: Cookie,Accept-Encoding,Authorization
-   RespHeader     Vary: Cookie,Accept-Encoding,Authorization
-   RespUnset      Vary: Cookie,Accept-Encoding,Authorization
-   RespHeader     Vary: Cookie,Accept-Encoding,Authorization
-   VCL_acl        MATCH debuggers "127.0.0.1"
-   RespHeader     X-Cache: MISS
-   VCL_return     deliver
-   Timestamp      Process: 1449491508.456478 0.278347 0.000027
-   RespUnset      Content-Length: 1645
-   RespUnset      Content-Encoding: gzip
-   RespHeader     Transfer-Encoding: chunked
-   Debug          "RES_MODE 68"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1449491508.456646 0.278514 0.000168
-   Debug          "XXX REF 2"
-   ESI_BodyBytes  1630
-   End            

*   << BeReq    >> 295049    
-   Begin          bereq 295048 pass
-   Timestamp      Start: 1449491507.524452 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /_fos_user_context_hash
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Host: test-myfonciav3.foncia.net
-   BereqHeader    Upgrade-Insecure-Requests: 1
-   BereqHeader    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
-   BereqHeader    Referer: http://test-myfonciav3.foncia.net/espace-client/espace-de-gestion/mon-bien/158
-   BereqHeader    Accept-Language: fr,en-US;q=0.8,en;q=0.6
-   BereqHeader    Backend: admin
-   BereqHeader    Via: 1.1 proxy.infra.lan (squid)
-   BereqHeader    Cache-Control: max-age=0
-   BereqHeader    X-Forwarded-Host: test-myfonciav3.foncia.net
-   BereqHeader    X-Forwarded-Server: test-myfonciav3.foncia.net
-   BereqHeader    x-user-hash: 6bed039020753a6150c4904753e0ffcd68600fa2c6855f950fff48ca8b79bbe9
-   BereqHeader    X-Foncia-User-Hash: 
-   BereqHeader    X-Foncia-Cookie-Accepted: false
-   BereqHeader    Surrogate-Capability: abc=ESI/1.0
-   BereqHeader    X-Forwarded-For: 192.168.1.121, 158.255.105.162, 192.168.133.3, 127.0.0.1, 127.0.0.1
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
-   BereqHeader    cookie: foncia_cookies_accepted=true; _dc_gtm_UA-64223993-1=1; is_logged_in=true; eZSESSID=33e28d33fefe2a33863a2c9ee462bf63; _dc_gtm_UA-64224692-1=1; _ga=GA1.3.1006489251.1449490794; ABTastySession=LiwioHashMRASN%3Anull%5E%7C%5ELiwioUTMC%3A1; ABTasty=ABT
-   BereqHeader    X-Foncia-Admin: false
-   BereqHeader    X-Varnish: 295049
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendOpen    14 ezpublish1(127.0.0.1,,82) 127.0.0.1 55719 
-   Backend        14 rr ezpublish1(127.0.0.1,,82)
-   Timestamp      Bereq: 1449491507.524669 0.000217 0.000217
-   Timestamp      Beresp: 1449491507.624882 0.100431 0.100213
-   BerespProtocol HTTP/1.1
-   BerespStatus   404
-   BerespReason   Not Found
-   BerespHeader   Date: Mon, 07 Dec 2015 12:31:47 GMT
-   BerespHeader   Server: Apache/2.2.15 (CentOS)
-   BerespHeader   X-Powered-By: PHP/5.6.10
-   BerespHeader   Cache-Control: no-cache
-   BerespHeader   Surrogate-Control: content="ESI/1.0"
-   BerespHeader   Vary: X-User-Hash,Accept-Encoding
-   BerespHeader   Content-Encoding: gzip
-   BerespHeader   Access-Control-Allow-Origin: *
-   BerespHeader   X-Front-Hostname: SDD110D012FEL
-   BerespHeader   Content-Length: 3425
-   BerespHeader   Connection: close
-   BerespHeader   Content-Type: text/html; charset=UTF-8
-   TTL            RFC 120 -1 -1 1449491508 1449491508 1449491507 0 0
-   VCL_call       BACKEND_RESPONSE
-   BerespHeader   X-Varnish-Backend: ezpublish1
-   BerespUnset    Surrogate-Control: content="ESI/1.0"
-   TTL            VCL -1 3600 0 1449491508
-   TTL            VCL 120 3600 0 1449491508
-   VCL_return     deliver
-   BerespUnset    Content-Length: 3425
-   Storage        malloc Transient
-   ObjProtocol    HTTP/1.1
-   ObjStatus      404
-   ObjReason      Not Found
-   ObjHeader      Date: Mon, 07 Dec 2015 12:31:47 GMT
-   ObjHeader      Server: Apache/2.2.15 (CentOS)
-   ObjHeader      X-Powered-By: PHP/5.6.10
-   ObjHeader      Cache-Control: no-cache
-   ObjHeader      Vary: X-User-Hash,Accept-Encoding
-   ObjHeader      Content-Encoding: gzip
-   ObjHeader      Access-Control-Allow-Origin: *
-   ObjHeader      X-Front-Hostname: SDD110D012FEL
-   ObjHeader      Content-Type: text/html; charset=UTF-8
-   ObjHeader      X-Varnish-Backend: ezpublish1
-   Fetch_Body     3 length -
-   Gzip           U F - 3425 13744 80 80 27331
-   Gzip           G F E 13744 5786 80 46208 46218
-   Timestamp      BerespBody: 1449491507.626957 0.102506 0.002075
-   BackendClose   14 ezpublish1(127.0.0.1,,82)
-   Length         5786
-   BereqAcct      1342 0 1342 389 3425 3814
-   End            

*   << Request  >> 295048    
-   Begin          req 295047 restart
-   Timestamp      Start: 1449491507.524353 0.000122 0.000000
-   ReqStart       127.0.0.1 54664
-   VCL_call       RECV
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   Debug          "XXXX HIT-FOR-PASS"
-   HitPass        2147516651
-   VCL_call       PASS
-   VCL_return     fetch
-   Link           bereq 295049 pass
-   Timestamp      Fetch: 1449491507.626968 0.102736 0.102615
-   RespProtocol   HTTP/1.1
-   RespStatus     404
-   RespReason     Not Found
-   RespHeader     Date: Mon, 07 Dec 2015 12:31:47 GMT
-   RespHeader     Server: Apache/2.2.15 (CentOS)
-   RespHeader     X-Powered-By: PHP/5.6.10
-   RespHeader     Cache-Control: no-cache
-   RespHeader     Vary: X-User-Hash,Accept-Encoding
-   RespHeader     Content-Encoding: gzip
-   RespHeader     Access-Control-Allow-Origin: *
-   RespHeader     X-Front-Hostname: SDD110D012FEL
-   RespHeader     Content-Type: text/html; charset=UTF-8
-   RespHeader     X-Varnish-Backend: ezpublish1
-   RespHeader     X-Varnish: 295048 295049
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespUnset      Vary: X-User-Hash,Accept-Encoding
-   RespHeader     Vary: ,Accept-Encoding
-   RespUnset      Vary: ,Accept-Encoding
-   RespHeader     Vary: Accept-Encoding
-   VCL_acl        MATCH debuggers "127.0.0.1"
-   RespHeader     X-Cache: MISS
-   VCL_return     deliver
-   Timestamp      Process: 1449491507.627003 0.102772 0.000036
-   RespHeader     Transfer-Encoding: chunked
-   Debug          "RES_MODE 38"
-   RespHeader     Connection: keep-alive
-   Link           req 295050 esi
-   Link           req 295052 esi
-   Link           req 295054 esi
-   Link           req 295056 esi
-   Link           req 295058 esi
-   Link           req 295060 esi
-   Link           req 295062 esi
-   Timestamp      Resp: 1449491508.456754 0.932523 0.829751
-   Debug          "XXX REF 1"
-   ESI_BodyBytes  2996
-   End

**Comment by ddeboer** [comment] 2015-12-07 21:44
Like @dbu already suspected: [our default accept header](http://foshttpcache.readthedocs.org/en/stable/varnish-configuration.html#user-context), `application/vnd.fos.user-context-hash` is missing here. For the user context event subscriber to work, the request must have the correct HTTP Accept header.

1. Can you post your FOSHttpCacheBundle config so we see whether you’re overriding the [accept option](https://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/user-context.html#accept)?

2. Did you [configure Varnish](http://foshttpcache.readthedocs.org/en/stable/varnish-configuration.html#varnish-user-context) so that the Accept header is set? Something like:

    ```c
    set req.http.accept = "application/vnd.fos.user-context-hash";
    ```

**Comment by supasteev0** [comment] 2015-12-07 21:53
We didn't override the base FOSHttpCacheBundle config at all (other than the config present in eZ Kernel), so the accept header is application/vnd.fos.user-context-hash only. The request by the way succeeds most of the time, but there are a few cases like this one where it fails.

Here is a part of the vcl we are using : 

// Custom User Hash 
    if (req.url ~ "^/espace-client"  || req.url == "/_foncia_user_context_hash") {
    	call custom_user_hash;
    }
else
{
	call ez_user_hash;
}

// Sub-routine to get client user hash, for context-aware HTTP cache.
sub ez_user_hash {

    // Prevent tampering attacks on the hash mechanism
    if (req.restarts == 0
        && (req.http.accept ~ "application/vnd.fos.user-context-hash"
            || req.http.x-user-hash
        )
    ) {
        return (synth(400));
    }

    if (req.restarts == 0 && (req.method == "GET" || req.method == "HEAD")) {
        // Anonymous user => Set a hardcoded anonymous hash
        if (!req.http.authorization && req.http.Cookie !~ "is_logged_in") {
            set req.http.X-User-Hash = "38015b703d82206ebc01d17a39c727e5";
        }
        // Pre-authenticate request to get shared cache, even when authenticated
        else {
            set req.http.x-fos-original-url    = req.url;
            set req.http.x-fos-original-accept = req.http.accept;
            set req.http.x-fos-original-cookie = req.http.cookie;

            // Clean up cookie for the hash request to only keep session cookie, as hash cache will vary on cookie.
            set req.http.cookie = ";" + req.http.cookie;
            set req.http.cookie = regsuball(req.http.cookie, "; +", ";");
            set req.http.cookie = regsuball(req.http.cookie, ";(eZSESSID[^=]*)=", "; \1=");
            set req.http.cookie = regsuball(req.http.cookie, ";[^ ][^;]*", "");
            set req.http.cookie = regsuball(req.http.cookie, "^[; ]+|[; ]+$", "");

            set req.http.accept = "application/vnd.fos.user-context-hash";
            set req.url = "/_fos_user_context_hash";

            // Force the lookup, the backend must tell how to cache/vary response containing the user hash

            return (hash);
        }
    }

    // Rebuild the original request which now has the hash.
    if (req.restarts > 0
        && req.http.accept == "application/vnd.fos.user-context-hash"
    ) {
        set req.url         = req.http.x-fos-original-url;
        set req.http.accept = req.http.x-fos-original-accept;
        set req.http.cookie = req.http.x-fos-original-cookie;

        unset req.http.x-fos-original-url;
        unset req.http.x-fos-original-accept;
        unset req.http.x-fos-original-cookie;

        // Force the lookup, the backend must tell not to cache or vary on the
        // user hash to properly separate cached data.

        return (hash);
    }
}

// Custom User Hash
sub custom_user_hash {
	// Prevent tampering attacks on the hash mechanism
     if (req.restarts == 0
		&& (req.http.accept ~ "application/vnd.fos.user-context-hash"
			|| req.http.x-user-hash
		)
	) {
		return (synth(400));
	}

    if (req.restarts == 0 && (req.method == "GET" || req.method == "HEAD")) {
        // Anonymous user => Set a hardcoded anonymous hash
       if (!req.http.authorization && req.http.Cookie !~ "is_logged_in") {
            set req.http.X-Custom-User-Hash = "anonymous";
        }
        // Pre-authenticate request to get shared cache, even when authenticated
        else {
            set req.http.x-fos-original-url    = req.url;
            set req.http.x-fos-original-accept = req.http.accept;
            set req.http.x-fos-original-cookie = req.http.cookie;

            // Clean up cookie for the hash request to only keep session cookie, as hash cache will vary on cookie.
            set req.http.cookie = ";" + req.http.cookie;
            set req.http.cookie = regsuball(req.http.cookie, "; +", ";");
            set req.http.cookie = regsuball(req.http.cookie, ";(eZSESSID[^=]*)=", "; \1=");
            set req.http.cookie = regsuball(req.http.cookie, ";[^ ][^;]*", "");
            set req.http.cookie = regsuball(req.http.cookie, "^[; ]+|[; ]+$", "");

            //set req.http.accept = "application/vnd.fos.user-context-hash";
            set req.url = "/_custom_user_context_hash";

            // Force the lookup, the backend must tell how to cache/vary response containing the user hash

            return (hash);
        }
    }

    // Rebuild the original request which now has the hash.
    if (req.restarts > 0 ) {
        set req.url         = req.http.x-fos-original-url;
        set req.http.accept = req.http.x-fos-original-accept;
        set req.http.cookie = req.http.x-fos-original-cookie;

        unset req.http.x-fos-original-url;
        unset req.http.x-fos-original-accept;
        unset req.http.x-fos-original-cookie;

        // Force the lookup, the backend must tell not to cache or vary on the
        // user hash to properly separate cached data.

        return (hash);
    }
}

sub vcl_deliver {
    // On receiving the hash response, copy the hash header to the original
    // request and restart.
    if (req.restarts == 0
        && resp.http.content-type ~ "application/vnd.fos.user-context-hash"
    ) {
        set req.http.x-user-hash = resp.http.x-user-hash;
        set req.http.X-Custom-User-Hash = resp.http.X-Custom-User-Hash;

        return (restart);
    }

    // If we get here, this is a real response that gets sent to the client.

    // Remove the vary on context user hash, this is nothing public. Keep all
    // other vary headers.
    set resp.http.Vary = regsub(resp.http.Vary, "(?i),? *x-user-hash *", "");
    set resp.http.Vary = regsub(resp.http.Vary, "^, *", "");
    if (resp.http.Vary == "") {
        unset resp.http.Vary;
    }

    // Sanity check to prevent ever exposing the hash to a client.
    unset resp.http.x-user-hash;
 unset resp.http.X-Custom-User-Hash;

    if (client.ip ~ debuggers) {
        if (obj.hits > 0) {
            set resp.http.X-Cache = "HIT";
            set resp.http.X-Cache-Hits = obj.hits;
        } else {
            set resp.http.X-Cache = "MISS";
        }
    }
}

**Comment by supasteev0** [comment] 2015-12-07 21:56
Our custom route /_custom_user_context_hash is a simple route, no accept headers are checked

**Comment by ddeboer** [comment] 2015-12-08 07:43
Your original problem was `Unable to find the controller for path "/_fos_user_context_hash`. This is caused by the UserContextSubscriber not matching the request. Because you only see this sometimes (while at others the path *does* match), the underlying cause is probably a missing Accept request header. This idea is supported by the fact that in your Varnish logs we nowhere find the `application/vnd.fos.user-context-hash` Accept header.

The `LostHeader …` log lines look quite suspicious: is your Varnish machine running low on memory or processing extremely long headers?

**Comment by supasteev0** [comment] 2015-12-08 07:54
Yes, the LostHeader is quite suspicious indeed, I don't where this come from... The system Varnish is running on is quite healthy actually and still has a lot of free memory.

**Comment by dbu** [comment] 2015-12-08 08:39
can you add more logging to the listener and whenver there is a request
for that hash url you check whether the accept header is indeed there,
and if it is not, log as many details as you can and check with varnish
each time if you have the LostHeader thing? if varnish is throwing away
headers, things will get difficult...

**Comment by dbu** [comment] 2016-01-04 16:21
@supasteev0 did you find anything more?

**Comment by supasteev0** [comment] 2016-01-06 17:38
@dbu yes we found a solution that seems to work.
Even with some logging added to the listener, we just could not explain why the application/vnd.fos.user-context-hash header was sometimes missing from the Varnish request.
The bug was taking place randomly but more often on pages with a lot of ESI (6 or 7).
We then  added a new parameter to the Varnish service :  -p workspace_client=327680
This solved the problem for now.
We are experiencing exactly the same problem on other ez5 projects with some ESI and front user connection. We will therefore try to apply the same Varnish configuration for these other projects.

**Comment by ddeboer** [comment] 2016-01-06 19:43
@supasteev0 Thanks for letting us know! Hopefully, it benefits others having similar problems. As the trouble didn’t seem to be caused by FOSHttpCache, I’m closing this issue.

**Closed by ddeboer** 2016-01-06 19:43 UTC
